### ISSUE TITLE
Add miningpoolhub coin

### ISSUE THREAD

**Issue by buntakunfumoffu** [felixbrucker/profitability-service#1]
Hi,
I just tested your software to switch to the most profitable algorithm and it works correctly.
Would it be possible to do the same thing but by coin with Whattomine or miningpoolhub with their api.
Ex with this address: http://miningpoolhub.com/index.php?page=api&action=getminingandprofitsstatistics

**Comment by felixbrucker** [comment]
it would indeed be possible (at least for mph it seems rather easy), but currently my time is sadly limited, in a few weeks maybe
also i want to rewrite the software a bit to support the selection of sites in the query (and not the system itself), so multiple systems can use different pools defined by themselves

**Comment by felixbrucker** [comment]
mph switching is supported now
