### ISSUE TITLE
Multi algo ?

### ISSUE THREAD

**Issue by polytone** [felixbrucker/profitability-service#2]
is this update Baikal mini to support mining below algo ?

    myriad-groestl
    blake2s
    cryptonight
    daggerhashimoto
    decred
    equihash
    groestl
    keccak
    lbry
    lyra2re
    lyra2rev2
    lyra2z
    neoscrypt
    nist5
    pascal
    quark
    qubit
    scrypt
    sha256
    sia
    skein
    skunk
    x11
    x11gost
    x13
    x15
    yescrypt

**Comment by felixbrucker** [comment]
Hi,

i do not own any baikal miner anymore and thus i have stopped developing the baikal-manager for quite some time now and it will not work with the current version of profitability service.

Regarding your question: asic/fpga miners only support a limited set of algorithms and only those can be switched. Mining other algos is not possible.
